/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'harikishore' at '2/8/16 2:39 PM' with Gradle 2.10
 *
 * @author harikishore, @date 2/8/16 2:39 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
