/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'harikishore' at '2/12/16 8:54 AM' with Gradle 2.10
 *
 * @author harikishore, @date 2/12/16 8:54 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
